remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: GY4006: Practicing Geographical Research
description: Geospatial/GIS research for Year 3 Geography students at the University of Limerick